Create controller with favourite movies.
maksmorgy/FilmsApp pull request #5
Opened 2022-01-30 13:39 UTC by maksmorgy

Create: FavouriteController and TabBar,
presenter for FavouriteController,
 CoreData model, CoreDataManager,
swipe for add movies to coreData model and swipe for remove movies from coreData model,

2022-02-01 12:28 UTC, vmytko requested changes

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/App/SceneDelegate.swift
> +        //(UIApplication.shared.delegate as? AppDelegate)?.saveContext()
Remove commented code

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/CoreData/Film_Data+CoreDataClass.swift
> +public class Film_Data: NSManagedObject {
Rename "Film_Data" to "FilmMO" (adding the abbreviation "MO" to the name of an entity is recommended by Apple and it means "Managed Object")

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/GeneralController/MainViewController.swift
> +
Consider using "NSLayoutConstraint.activate" method for activating constraints instead of setting "isActive" property

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/GeneralController/MainViewController.swift
>          self.view.addSubview(moviesCollectionsTableView)
"self" can be omitted.

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +        favouriteTableView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
Consider using "NSLayoutConstraint.activate" method for activating constraints instead of setting "isActive" property

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +        favouriteTableView.translatesAutoresizingMaskIntoConstraints = false
This property was already set to false in the initialization block, it can be removed.

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +        self.view.addSubview(favouriteTableView)
"self" can be omitted

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +    let cell = "favouriteCell"
Rename to "cellReuseIdentifier"

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +    var films = [Film_Data]()
Property "films" should be removed from the controller as it already exists in the presenter. Create method "filmAtIndex(_ index: Int)" in presenter and use it when creating cell in "cellForRow" datasource method.

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +    var favouriteTableView: UITableView = {
Make favouriteTableView property a constant, as it will not be changed after initialization.

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +        let table = UITableView()
Rename to "tableView"

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +    let context = CoreDataManager.instance.persistentContainer.viewContext
Only the presenter should be able to access context. Remove it from controller

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +
Remove empty lines

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +            self.favouriteTableView.reloadData()
TableView should be reloaded when the presenter returns new films via the delegate method.

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +    override func viewWillAppear(_ animated: Bool) {
Call super.viewWillAppear

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +        let deleteAction = UIContextualAction(style: .destructive, title:  "Delete", handler: { (ac:UIContextualAction, view:UIView, success:(Bool) -> Void) in
No need to explicitly add types to closure parameters. Should look like: (action, view, completionHandler)

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/GeneralController/MainViewController.swift
> +        newViewController.listTableView.reloadData()
Reloading of "listTableView" should be performed in newViewController

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/GeneralController/MainViewController.swift
> +                let images: [URL] = self.presenter?.filmsCollection?[indexPath.section].films.map({ film in
The presenter should not be optional, because it is passed via initializer, so it is guaranteed to have some value.

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/GeneralController/MainViewController.swift
>                  return image! }) ?? []
It is not recommended to unwrap optional value via forced unwrapping. In this case use "compactMap" instead of "map" that you will be able to return "imageURL" without unwrapping.

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/GeneralController/MainViewController.swift
>          self.moviesCollectionsTableView.isUserInteractionEnabled = true
"self" can be omitted

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/TabBarVC/TabBarController.swift
> +        self.tabBar.tintColor = .black
This configuration must be done in "SceneDelegate". Also, when creating adding controllers to the tabBarController, firstly you need to create UITabBarItem and then assign it to each view controller that you want to add to the tabBarController, after all the viewController are configured, use "setViewControllers" in UITabBarViewController

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/MovieListCell.swift
> +        if  let image: UIImage = image {
Use "guard let" statement instead of "if let" and no need to explicitly adding type "UIImage"

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/MovieListCell.swift
> +        }
Fix alignment

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/MovieListCell.swift
> +        loadingIndicator.center = CGPoint(x: self.contentView.bounds.width / 2, y: self.contentView.bounds.height / 2)
Configure layout of "loadingIndicator" using constraints

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/ListViewController.swift
> +                if let data = try? Data(contentsOf: url!) {
Use "guard let" statement and combine creating of data and image in one statement. Also remove force unwrapping of a "url" property

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/ListViewController.swift
> +
Consider using "NSLayoutConstraint.activate" method for activating constraints instead of setting "isActive" property

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/ListViewController.swift
> +        self.view.addSubview(listTableView)
"self" should be omitted.

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/ListViewController.swift
> +        let myDel = UIContextualAction(style: .normal, title: "Favourite") { (_, _, complitionHand) in
Rename to "deleteAction"

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/ListViewController.swift
> +        }
Fix alignment

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/ListViewController.swift
> +
Remove empty line

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/ListViewController.swift
> +            if let data = try? Data(contentsOf: (self.data.films[indexPath.row].imageURL)!) {
Remove forced unwrapping

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/ListViewController.swift
> +                    complitionHand(true)
Rename to "completionHandler"

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/ListViewController.swift
>      let cell = "cell"
Rename to "cellReuseIndentifier"

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/ListController/ListViewController.swift
> +            CoreDataManager.instance.saveContext()
Context saving must be done in the presenter

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteCell.swift
> +            if let image = UIImage(data: (content?.filmImage)!){
Remove forced unwrapping

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteCell.swift
> +        loadingIndicator.center = CGPoint(x: self.contentView.bounds.width / 2, y: self.contentView.bounds.height / 2)
Configure layout using constraints

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteCell.swift
> +    var loadingIndicator = UIActivityIndicatorView(style: .large)
These properties should be constants

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/Presenter/FavouritePresenter.swift
> +    let context = CoreDataManager.instance.persistentContainer.viewContext
Add "private" access modifier

2022-02-01 12:28 UTC, vmytko commented on FilmsApp/Presenter/DetailPresenter.swift
> +                let movie = DetailFilm(id: movieResponse.id ?? "", originalTitle: movieResponse.title ?? "", genres: movieResponse.genres ?? "", countries: movieResponse.countries ?? "", rating: movi
Consider renaming "DetailFilm" to "FilmDetails"

2022-02-10 15:24 UTC, vmytko requested changes

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/App/SceneDelegate.swift
> +        favouriteVC.tabBarItem = favouriteTabBarItem
Create a separate function for controller creation which will take two parameters "title" and "image".

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/App/SceneDelegate.swift
> +        let homeTabBarItem = UITabBarItem()
Use another initializer where you can pass the image and title instead of setting them after the tabBarItem is created.

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/App/SceneDelegate.swift
> +        _ = UINavigationController(rootViewController: mainVC)
Do you need this line of code?

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/CoreData/CoreDataManager.swift
> +    func delete(film: MOFilm) {
As described in previous comments regarding rename managed objects you should rename it to "FilmMO' as Apple recommends

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/CoreData/CoreDataManager.swift
> +        let container = NSPersistentContainer(name: "MOFilm")
You should not rename the persistent container to FilmMO because the persistent container and managed object are different things. Usually, the name of the persistent container is the same as the name of a project.

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Detail/DetailController.swift
> +
Remove empty line

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Detail/DetailController.swift
> +        addObjects()
Rename this method to "setupViewHierarchy". "addObjects" name is too generic.

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Detail/DetailController.swift
> +    }
This configuration can be put in the initialization blocks of each textView.

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Detail/DetailPresenter.swift
> +    internal var filmDescription: FilmDetails?
Internal access modifier is used by default, it can be omitted.

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Detail/DetailPresenter.swift
> +    var filmDescription: FilmDetails? { get set }
Rename it to "filmDetails"

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Favourite/FavouriteCell.swift
>      }
Layout setup should be done in the initializer.

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Favourite/FavouriteCell.swift
> +    private let loadingIndicator = UIActivityIndicatorView(style: .large)
Do you need an activity indicator in FavouriteCell?

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Favourite/FavouriteCell.swift
>          DispatchQueue.main.async {
Try removing dispatching from here, it should already be on the main queue.

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Favourite/FavouriteCell.swift
>                  self.favouriteImage.image = .none
The film title should be set regardless the film image exists.

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Main/MainViewController.swift
> +            return customCell
It is already on the main queue, no need to dispatch

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Main/MainViewController.swift
> +    let cellReuseIdentifier = "mainCell"
Make private

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Main/MainCell.swift
> +    lazy var filmsCollectionView: UICollectionView = {
Should be private

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Main/HeaderMainView.swift
> +    }
Create UILabel the same way you are creating it in other UI components. Make a separate property for a label.

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Main/CollectionListCell.swift
> +            if let data = try? Data(contentsOf: (film?.imageURL)!) {
Remove forced unwrapping

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Main/CollectionListCell.swift
> +        }
Fix alignment

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/MovieListCell.swift
> +        DispatchQueue.main.async {
It should already be on the main queue

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/MovieListCell.swift
> +                if let data = try? Data(contentsOf: url) {
Here you need to dispatch to the global queue, and after that dispatch back to the main queue when Data is fetched.

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/MovieListCell.swift
> +                    self.filmListLabel.text = title
The film title should be set right away without waiting for the image to be fetched

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/MovieListCell.swift
> +                    self.setupLayoutFilm()
It should be called in the initalizer

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/MovieListCell.swift
> +    func updateAppearanceFor (film: Film?) {
Remove empty space

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/ListViewController.swift
> +            DispatchQueue.main.async {
Should already be in the main queue. Dispatching can be removed

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/ListViewController.swift
> +        let filmId = self.presenter.filmAtIndex(index: indexPath.row)?.filmId
"self" can be omitted

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/ListViewController.swift
> +        self.navigationController?.pushViewController(newViewController, animated: true)
"self" can be omitted

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/ListViewController.swift
> +        listTableView.deselectRow(at: indexPath, animated: true )
Remove empty space after "true'

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/ListViewController.swift
> +        self.listTableView.reloadData()
You should dispatch to the main queue here

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/ListViewController.swift
> +        cell.updateAppearanceFor(film: self.presenter.filmAtIndex(index: indexPath.row))
"self" can be omitted

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/ListViewController.swift
> +    var presenter: ListPresenterProtocol
It should be private and constant

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/ListPresenter.swift
> +    init(managerCD: CoreDataManager, data: FilmsCollection) {
Rename "managerCD" to "coreDataManager"

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/ListPresenter.swift
> +    private let films: [Film]?
Films array should not be optional

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/List/ListPresenter.swift
> +    func numberOffilms() -> Int
Use "camel case" when naming functions and other entities. Should be "numberOfFilms"

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Favourite/FavouritePresenter.swift
> +    init(managerCD: CoreDataManager) {
Rename "managerCD" to "coreDataManager"

2022-02-10 15:24 UTC, vmytko commented on FilmsApp/View/Favourite/FavouritePresenter.swift
> +        self.films?.remove(at: index)
"self" can be omitted

2022-02-10 15:37 UTC, vmytko commented on FilmsApp/View/FavouriteController/FavouriteController.swift
> +    override func viewWillAppear(_ animated: Bool) {
When calling super.viewWillAppear pass the "animated" property that was passed to this "viewWillAppear" method

2022-02-11 07:21 UTC, maksmorgy commented on FilmsApp/View/List/MovieListCell.swift
> +        DispatchQueue.main.async {
DispatchQueue.main.async {
It's not on the main queue?

2022-02-11 11:48 UTC, vmytko approved these changes

2022-02-11 11:52 UTC, merged